### ISSUE TITLE
Loopholes

### ISSUE THREAD

**Issue by SquidDev** [SquidDev-CC/Taken-Map#2]
## General flaws
- [x] Can override `asset.eq` and other methods.
- [x] Events are triggered in spectator mode.
- [x] Can inject `end if false then` to end a function. The best way to avoid probably parse the code and check that there isn't any code in the top level function/
- [x] Zombies can burn if left long enough.
## Particular levels
- [x] **Chapter 2:** Can jump over lava
- [x] **Chapter 5:** Mines not placed on y = 3
- [x] **Chapter 7:** Can walk diagonally

**Comment by BombBloke** [comment]
Walking diagonally still works for chapter 7 - is it supposed to be fixed, or did you opt to ignore?

The only proper method of dealing with it (that I can see) would be to rig world.line to ensure that all line-blocks placed have at two other line-blocks touching their sides (other than the ends). Basically pad over the gaps where need be.

**Comment by SquidDev** [comment]
IIRC I originally fixed it by moving the lines around a little. However I recently resized the arena which may have thrown things off a little. I'll have another prod now.
